### PR TITLE
Update to model 0.0.172

### PR DESCRIPTION
**Pull request by jhernand**
The more relevant changes in the new version of the model are the
following:

- Remove deprecated `SKUs` endpoint.
- Remove deprecated quota summary resource and type.
- Add QuotaVersion to ClusterAuth.
- Allow adding/removing operator roles.

### CODE REVIEW

**Comment by jhernand** [comment]
FYI: @markturansky

**Comment by jhernand** [comment]
@cristianoveiga in order to make this update I had to remove the `examples/list_quota_summary.go` example. Would be nice if you can replace it with something similar that uses the current API.

**Comment by cristianoveiga** [comment]
> @cristianoveiga in order to make this update I had to remove the `examples/list_quota_summary.go` example. Would be nice if you can replace it with something similar that uses the current API.

thank you very much @jhernand !

@markturansky, I understand that the quota_cost endpoint should be used from now on. Should we add a list_quota_cost.go example?

**Comment by markturansky** [comment]
@cristianoveiga yes, that sounds like a good example to include if you wish.

**Comment by cristianoveiga** [comment]
perfect, thanks @markturansky. I will work on that and submit a new PR .

**Pull request merged**
