### PR TITLE
OCM-209 | chore: release v0.1.354

### PR DESCRIPTION
**Pull request by osherdp**
Upgrade to latest model version v0.0.299

Notes:
https://github.com/openshift-online/ocm-api-model/releases/tag/v0.0.298
https://github.com/openshift-online/ocm-api-model/releases/tag/v0.0.299

This allows setting cluster-autoscaler parameters via API. This code is intended to be used by the depending clients (primarily ``rosa`` CLI, but also the terraform provider and some automated API tests).

Depends on https://github.com/openshift-online/ocm-api-model/pull/790.

### CODE REVIEW

**Comment by zgalor** [comment]
There's also a version.go and changes.doc file that needs to update with the new version

**Comment by osherdp** [comment]
drafted it temporarily, because we might want to add another change to the api-model describing how ``"autoscaler"`` values are completely overridden on ``PATCH /api/clusters_mgmt/v1/clusters`` requests

**Comment by osherdp** [comment]
cc @tzvatot @ciaranRoche

**Comment by osherdp** [comment]
Converting to draft because I might want to do another change in the model

**Review by zgalor — APPROVED** [review]
LGTM

**Pull request merged**
