### PR TITLE
Update to model v0.0.62

### PR DESCRIPTION
**Pull request by vkareh**
Also added a commit for the next v0.1.106 release

### CODE REVIEW

**Comment by igoihman** [comment]
```
 github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1
18:39:18 ../clustersmgmt/v1/log_client.go:89:2: undefined: get
18:39:18 ../clustersmgmt/v1/log_client.go:101:2: undefined: get
1
```

**Comment by vkareh** [comment]
Yeah I saw that, still trying to figure out what the issue is

**Comment by vkareh** [comment]
It comes from this: https://github.com/openshift-online/ocm-api-model/pull/184

Seems like the metamodel has a hard time with arbitrary parameters on the `Get` method...

**Comment by vkareh** [comment]
@igoihman - things look green now. Please take a look

**Pull request merged**
