### PR TITLE
chore(version): bump to 0.1.225 [SDB-2509]

### PR DESCRIPTION
**Pull request by georgettica**
-  MatchJQ should require at least one result 
- Update to model 0.0.158:
  - Adding subnetworks to vpc inquiry
  - Add statuses path to service model, add some comments.
  - [SDB-2509] Update OSL API schema to be compatible with ocm-sdk-go

### CODE REVIEW

**Comment by georgettica** [comment]
local `go test ./...` succeeds
trying to download ginkgo to verify why this fails

**Comment by georgettica** [comment]
seems that containerized solution doesn't work because the tests use `docker`

**Comment by georgettica** [comment]
```
$ make tests
ginkgo -r
[1639917940] Client - 101/101 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 3.589213993s PASS
[1639917940] Authentication - 96/96 specs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 3.38397161s PASS
[1639917940] Configuration - 60/60 specs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 100.46059ms PASS
[1639917940] Data - 26/26 specs •••••••••••••••••••••••••• SUCCESS! 754.933µs PASS
[1639917940] Database - 4/4 specs •••• SUCCESS! 319.53µs PASS
[1639917940] Internal - 35/35 specs ••••••••••••••••••••••••••••••••••• SUCCESS! 120.794152ms PASS
[1639917940] Leadership - 20/20 specs •••••••••••••••••••• SUCCESS! 17.137051422s PASS
[1639917940] Logging - 12/12 specs •••••••••••• SUCCESS! 373.938µs PASS
Failed to compile asciidoc:

main module (github.com/openshift-online/ocm-sdk-go) does not contain package github.com/openshift-online/ocm-sdk-go/metamodel/pkg/asciidoc

Ginkgo ran 9 suites in 48.149044324s
Test Suite Failed

XXXXX

make: *** [tests] Error 1
```

**Comment by jhernand** [comment]
@georgettica the tests failure that you see are a side effect of cloning and building the metamodel tool as part of the tests, it is not related to your changes. I will try to fix that. Meanwhile `v0.1.225` is tagged now.

**Pull request merged**
