### PR TITLE
Bump sdk version

### PR DESCRIPTION
**Pull request by tzvatot**
@igoihman PTAL

### CODE REVIEW

**Comment by vkareh** [comment]
what happened with the changelog?

**Comment by tzvatot** [comment]
> what happened with the changelog?

what do you mean?

**Comment by vkareh** [comment]
The change was updating an existing number, not adding a new version, was there an error in the previous bump?

**Comment by tzvatot** [comment]
> The change was updating an existing number, not adding a new version, was there an error in the previous bump?

Yeah, for some unknown reason v.0.1.134 wasn't able to download using go-get. The same procedure worked for 135...

**Comment by vkareh** [comment]
ah got it, thanks

**Pull request merged**
