### PR TITLE
Update to model version 0.0.115

### PR DESCRIPTION
**Pull request by bvulaj**
Related PR: https://github.com/openshift-online/ocm-api-model/pull/345/files

Note that this also contains changes from: https://github.com/openshift-online/ocm-api-model/commit/9d3e155943dcadc2a00127af8bce7e1bb848caf1

### CODE REVIEW

**Comment by bvulaj** [comment]
@zgalor please take a look

**Comment by tiwillia** [comment]
PR Check failure:
```
20:41:56 ./get_cluster_metrics.go:73:20: cluster.Metrics undefined (type *"github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1".Cluster has no field or method Metrics)
```

**Comment by zgalor** [comment]
@tzvatot Is that related to the metrics removal change you made?

**Comment by tzvatot** [comment]
@zgalor @tiwillia yes, the new model includes another change and needs to be reflected by fixing `get_cluster_metrics.go`.

**Comment by tiwillia** [comment]
@tzvatot We are blocking teams by not being able to update the SDK - Are you planning to submit a fix quickly or should we revert the ocm-api-model changes that are breaking the SDK?

**Comment by jhernand** [comment]
@tiwillia The fix to update to the new version of the model should be included in this change. Delete the `examples/get_cluster_metrics.go` file.

**Comment by jhernand** [comment]
I am merging this. But next time please squash the commits for this kind of changes.

**Pull request merged**
