### PR TITLE
Update to model 0.0.52

### PR DESCRIPTION
**Pull request by igoihman**
The more relevant changes in the new version of the model are the
following:

- Update to new subscrition model endpoints

### CODE REVIEW

**Comment by igoihman** [comment]
[test]

**Comment by igoihman** [comment]
@gshilin-sdb @tiwillia FYI

**Comment by gshilin-sdb** [comment]
[test]

**Comment by igoihman** [comment]
@gshilin-sdb you first need to create a new release in `ocm-api-model`

**Comment by igoihman** [comment]
@gshilin-sdb you first need to create a new release in `ocm-api-model`

**Comment by gshilin-sdb** [comment]
[test]

**Pull request merged**
