### PR TITLE
Update to model vesion 0.0.61

### PR DESCRIPTION
**Pull request by gshilin-sdb**

### CODE REVIEW

**Comment by igoihman** [comment]
you also need to run `make generate` and add the changed files.

**Comment by vkareh** [comment]
Can we /hold this for a bit? I'd like to cut a new release of ocm-api-model to include the changes for the subscription notification. Sorry!

**Comment by gshilin-sdb** [comment]
Will you create PR by yourself? Please update me

**Comment by vkareh** [comment]
@gshilin-sdb - I've released v0.1.106 with all the new changes from the model and metamodel. Closing this. Thanks!

**Pull request closed without merging**
