### PR TITLE
Bump ocm-api-model to v0.0.259

### PR DESCRIPTION
**Pull request by tzvatot**
Related: SDA-8281

@zgalor @oriAdler PTAL

### CODE REVIEW

**Comment by oriAdler** [comment]
Can we please have this one https://github.com/openshift-online/ocm-api-model/pull/696 in this version as well?

**Comment by tzvatot** [comment]
> Can we please have this one [openshift-online/ocm-api-model#696](https://github.com/openshift-online/ocm-api-model/pull/696) in this version as well?

No, it's not merged and not included in v0.0.259.

**Comment by zgalor** [comment]
> > Can we please have this one [openshift-online/ocm-api-model#696](https://github.com/openshift-online/ocm-api-model/pull/696) in this version as well?
> 
> No, it's not merged and not included in v0.0.259.

If you can wait till @oriAdler release 0.0.260 we can add it here

**Comment by zgalor** [comment]
LGTM

**Pull request merged**
