### PR TITLE
Release 0.1.287

### PR DESCRIPTION
**Pull request by oriAdler**
Related: [SDA-6766](https://issues.redhat.com/browse/SDA-6766)

### CODE REVIEW

**Comment by oriAdler** [comment]
@zgalor @etabak PTAL

**Comment by tzvatot** [comment]
@oriAdler I'm missing the version file update.

**Comment by oriAdler** [comment]
> @oriAdler I'm missing the version file update.

Added, thanks.

**Comment by tzvatot** [comment]
LGTM

**Pull request merged**
