### PR TITLE
Add some webrca examples

### PR DESCRIPTION
**Pull request by djberg96**
Some example programs I created for webrca.

### CODE REVIEW

**Comment by djberg96** [comment]
@jhernand It doesn't look like the current test failure is related. Any ideas?

**Comment by djberg96** [comment]
On a side note, when I built this locally I had to use `WebRca` instead of `WebRCA`. Not a huge deal, just thought that was strange.

**Review by jhernand — APPROVED** [review]
This is grea. Than you @djberg96.

**Comment by jhernand** [comment]
That `WebRCA` method is the only part of the code that isn't automatically generated from the code. I wrote it manually I assumed you would want to use the normal rules for initialisms in Go: all uppercase. I guess that when you wrote this locally you decided to use `WebRca` instead. I don't have a strong opinion; if you prefer `WebRca` go ahead and submit a pull request to change it.

**Comment by djberg96** [comment]
@jhernand `WebRCA` is probably expected, so I'm fine with leaving it. Thanks!

**Pull request merged**
